### ISSUE TITLE
Errore all'avvio di index.js

### ISSUE THREAD

**Issue by LolloMazzy** [roccomuso/rpi-fan#1]
module.js:339
throw err;
^

Error: Cannot find module 'onoff'
at Function.Module._resolveFilename (module.js:337:15)
at Function.Module._load (module.js:287:25)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at Object.<anonymous> (/home/pi/rpi-fan/index.js:6:12)
at Module._compile (module.js:435:26)
at Object.Module._extensions..js (module.js:442:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:311:12)
at Function.Module.runMain (module.js:467:10)

Questo è quello che visualizzo quando dò da terminale node `index.js`

**Comment by roccomuso** [comment]
Hai fatto `npm install` nella directory prima? per installare le dipendenze necessarie. Verrà a quel punto creata la directory `node_modules`

**Comment by LolloMazzy** [comment]
Grazie perchè sono riuscito a far partire il software ma penso di avere ancora qualche problema hardware e mi viene il dubbio di aver fatto confusione coi collegamenti. Posto lo schema.
![schermata 2018-10-06 alle 17 28 20](https://user-images.githubusercontent.com/10534882/46572922-24847680-c98e-11e8-863a-adf63a2914ed.png)

Questo è il mio config.json

`{
        "PIN_NUMBER": 11,
        "REFRESH_TIME": 3,
        "TEMPERATURE_THRESHOLD": 40.0,
        "WEB_SERVER": true,
        "SERVER_PORT": 4949,
        "FORBIDDEN_INTERVAL": {
                "hour": "00:00",
                "interval": 11
        }
}`

**Comment by roccomuso** [comment]
Lo shema sembra corretto, per capire se è un problema del software, potresti attivare il pin 11 (gpio 17) con il software in python o altri tool che l'os mette a disposizione e vedere se la ventola si aziona.

**Comment by LolloMazzy** [comment]
Premetto che la ventola è funzionante, l'unico neo è che chiede 12v 0.10A ma sempre alimentata a 5V e andava solamente piu lenta.

Comunque pilotando da terminale i pin la ventola resta comunque ferma.
Ho impostato anche il pin 11 (GPIO17) come output e poi pio `-g write 11 1` switchandolo piu volte tra 0 e 1 ma il risultato era lo stesso.

**Comment by roccomuso** [comment]
Occhio a non fare confusione fra la numerazione fisica dei pin e quella sw dei gpio

**Comment by LolloMazzy** [comment]
Ciao, ho risolto il mio problema sostiuento il transistor con un NPN S8050.
Ma ho un ulteriore problema....la ventola rimane sempre accesa: la soglia è impostata a 40*, al superamento si accendo ma quando si abbassa non si spegne.
Ho letto che rimane accesa per 5 min per non fare accendi/spegni continui ma qui non spegne per nulla. La funzione interessata è in index.js a riga 20?

**Comment by roccomuso** [comment]
E' codice vecchissimo che andrebbe sicuramente aggiustato.
Il punto è, se vedi i log in console allora entra in quel flow.
vedi i log? Quando si dovrebbe spegnere la ventola lo vedi il log ` .... - Fan OFF! - ...` ?

**Comment by LolloMazzy** [comment]
Si lo trovo nel file INDEX.JS

**Comment by roccomuso** [comment]
intendo in console dopo l'esecuzione dello script, vedi i log?

**Comment by LolloMazzy** [comment]
NO! Non appare più anche se sulla pagina web nello stato della ventola si legge OFF
